import { ArrowDown, ArrowUp, Calendar, Plus, Target } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { Empty, Modal, PageHeader, Spinner } from '../components/UI';
import { useApi } from '../hooks';
import { api, money, shortDate } from '../lib';

type Movement = { id: string; type: string; amount: string; date: string };
type Goal = { id: string; name: string; targetAmount: string; currentAmount: number; progress: number; deadline?: string; type: string; movements: Movement[] };
const goalLabels: Record<string,string> = { EMERGENCY_FUND: 'Fundo de emergência', GENERAL_SAVINGS: 'Poupança geral', INVESTMENT: 'Investimento', FAMILY_GOAL: 'Objetivo familiar' };
export default function SavingsPage() {
  const [modal, setModal] = useState<{ kind: 'goal' | 'movement'; goal?: Goal } | null>(null);
  const { data, loading, reload } = useApi<Goal[]>('/savings-goals', []);
  return <div className="page"><PageHeader title="Poupança e objetivos" subtitle="Cada contribuição aproxima a família dos seus planos." actions={<button className="btn primary" onClick={() => setModal({ kind: 'goal' })}><Plus /> Novo objetivo</button>} />
    {loading ? <Spinner /> : data.length ? <div className="goals-grid">{data.map((x) => <article className="panel goal-card" key={x.id}><div className="goal-icon"><Target /></div><span className="eyebrow">{goalLabels[x.type]}</span><h2>{x.name}</h2><div className="goal-amount"><strong>{money(x.currentAmount)}</strong><span>de {money(x.targetAmount)}</span></div><div className="progress purple"><span style={{ width: `${x.progress}%` }} /></div><div className="goal-meta"><strong>{x.progress.toFixed(0)}% concluído</strong>{x.deadline && <span><Calendar /> {shortDate(x.deadline)}</span>}</div><button className="btn secondary full" onClick={() => setModal({ kind: 'movement', goal: x })}>Adicionar movimento</button>{x.movements[0] && <div className="last-movement">{x.movements[0].type === 'CONTRIBUTION' ? <ArrowUp /> : <ArrowDown />}<span>Último movimento</span><strong>{money(x.movements[0].amount)}</strong></div>}</article>)}</div> : <Empty title="Ainda sem objetivos" text="Criem o fundo de emergência ou o próximo objetivo da família." />}
    {modal?.kind === 'goal' && <Modal title="Novo objetivo" onClose={() => setModal(null)}><form className="form-grid" onSubmit={async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const body: Record<string, any> = Object.fromEntries(new FormData(e.currentTarget)); body.targetAmount = Number(body.targetAmount); if (!body.deadline) delete body.deadline; else body.deadline = new Date(String(body.deadline)).toISOString(); await api('/savings-goals', { method: 'POST', body: JSON.stringify(body) }); setModal(null); reload(); }}><label className="span-2">Nome do objetivo<input name="name" required placeholder="Ex.: Reserva de 6 meses" /></label><label>Valor alvo<input name="targetAmount" type="number" min=".01" required /></label><label>Prazo<input name="deadline" type="date" /></label><label className="span-2">Tipo<select name="type">{Object.entries(goalLabels).map(([key,value]) => <option value={key}>{value}</option>)}</select></label><div className="form-actions span-2"><button type="button" className="btn secondary" onClick={() => setModal(null)}>Cancelar</button><button className="btn primary">Criar objetivo</button></div></form></Modal>}
    {modal?.kind === 'movement' && <Modal title={`Movimento · ${modal.goal!.name}`} onClose={() => setModal(null)}><form className="form-grid" onSubmit={async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const body: Record<string, any> = Object.fromEntries(new FormData(e.currentTarget)); body.amount = Number(body.amount); body.date = new Date(String(body.date)).toISOString(); await api(`/savings-goals/${modal.goal!.id}/movements`, { method: 'POST', body: JSON.stringify(body) }); setModal(null); reload(); }}><label>Tipo<select name="type"><option value="CONTRIBUTION">Contribuição</option><option value="WITHDRAWAL">Retirada</option></select></label><label>Valor<input name="amount" type="number" min=".01" required /></label><label>Data<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)} /></label><label>Observações<input name="notes" /></label><div className="form-actions span-2"><button type="button" className="btn secondary" onClick={() => setModal(null)}>Cancelar</button><button className="btn primary">Registar</button></div></form></Modal>}
  </div>;
}
